### PR TITLE
[metaroom_xml_parser] Added images to label data structure

### PR DESCRIPTION
**Pull request by nilsbore**

### CODE REVIEW

**Comment by nilsbore** [comment]
@RaresAmbrus can you have a look at this and merge if OK?

**Comment by nilsbore** [comment]
@RaresAmbrus how is it going with this? I'm thinking about adding the masks and depth images to the data structure.

**Comment by nilsbore** [comment]
I added the masks to the data structure now also, see previous commit.

**Comment by RaresAmbrus** [comment]
Looks good!

**Pull request merged**
